[package]
name = "portman_core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
prost = "0.14.1"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
tonic = "0.14.2"
tonic-prost = "0.14.2"

[build-dependencies]
tonic-prost-build = "0.14.2"
